### ISSUE TITLE
Курсы на Youtube

### ISSUE THREAD

**Issue by devdimit** [programming086/note-course#1]
Добрый день. Часто смотрел ваши курсы на youtube, но канал  сейчас стал недоступен. Можно узнать, что будет с курсами? Будут ли они продолжаться и, если да, то где?

**Comment by rbrovko** [comment]
Добрый день!
Надеюсь все будет отлично. Решаю этот вопрос с ложным срабатыванием алгоритмов YouTube. Как только появятся какие-то новости - сообщу.
Спасибо.

**Comment by programming086** [comment]
https://t.me/programming086/112

**Comment by rbrovko** [comment]
@devdimit окончательно сменили платформу. Курсы переехали на dailymotion.com. [Канал Programming](https://www.dailymotion.com/programming086)
